project:
  type: website

website:
  title: "Final-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - models.qmd
      - sources.qmd
      - text: "Positions"
        menu: 
          - goalkeeper.qmd
          - defense.qmd
          - midfield.qmd
          - offense.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



